LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES:= am_fend_test.c

LOCAL_MODULE:= aml_fend_test
LOCAL_LICENSE_KINDS := SPDX-license-identifier-GPL-2.0+ SPDX-license-identifier-LGPL-2.0+
LOCAL_LICENSE_CONDITIONS := notice

LOCAL_MODULE_TAGS := optional

#LOCAL_MULTILIB := 32
#LOCAL_CFLAGS+=-DANDROID -DAMLINUX -DCHIP_8226M -DLINUX_DVB_FEND
LOCAL_CFLAGS+=-DANDROID -DAMLINUX -DLINUX_DVB_FEND
LOCAL_C_INCLUDES :=  $(LOCAL_PATH)/../../include/
LOCAL_SHARED_LIBRARIES := libamdvr.product liblog libc

include $(BUILD_EXECUTABLE)

