LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_VENDOR_MODULE := true

LOCAL_SRC_FILES:= am_fend_test.c

LOCAL_MODULE:= aml_fend_test

LOCAL_MODULE_TAGS := optional

#LOCAL_MULTILIB := 32
#LOCAL_CFLAGS+=-DANDROID -DAMLINUX -DCHIP_8226M -DLINUX_DVB_FEND
LOCAL_CFLAGS+=-DANDROID -DAMLINUX -DLINUX_DVB_FEND

LOCAL_SHARED_LIBRARIES := liblog libc

include $(BUILD_EXECUTABLE)

